# Generated by Django 3.0.7 on 2021-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0018_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Avilabel_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Height',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Item_Weight',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Package_Dimensions',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Stock', 'Out Stock')], default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Width',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seeds_per_pack',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_3',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_4',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_5',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_6',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_7',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wholesaleproduct',
            name='subcategory',
            field=models.CharField(default='', max_length=100),
        ),
    ]
