# Generated by Django 3.0.7 on 2021-04-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_auto_20210331_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_visits',
            field=models.IntegerField(default=0),
        ),
    ]
