# Generated by Django 3.0.7 on 2021-04-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0026_auto_20210403_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_Categories',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='slug',
        ),
    ]
