# Generated by Django 3.0.7 on 2021-04-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0032_auto_20210404_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_Categories',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='slug',
        ),
    ]
