# Generated by Django 3.0.7 on 2021-04-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0033_auto_20210404_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='sub_Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_visits',
        ),
    ]
