# Generated by Django 3.0.7 on 2021-04-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0035_auto_20210404_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
