# Generated by Django 3.0.7 on 2021-04-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0036_auto_20210404_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
