# Generated by Django 3.0.7 on 2021-04-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0038_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
