# Generated by Django 3.0.7 on 2021-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='disease_img')),
                ('introduction', models.CharField(max_length=50000)),
                ('symptoms', models.CharField(max_length=50000)),
                ('treatment', models.CharField(max_length=50000)),
                ('resion', models.CharField(max_length=50000)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
