# Generated by Django 3.0.7 on 2021-04-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
